name: flutter_busappall
description: "Integrated bus guide and location guide app"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # Location and mapping (essential)
  geolocator: ^13.0.2
  flutter_map: ^6.1.0
  latlong2: ^0.9.1
  google_maps_flutter: ^2.10.1

  # Storage and preferences (for settings)
  shared_preferences: ^2.5.3
  path_provider: ^2.1.4

  # Network and HTTP (for API and map tiles)
  http: ^1.4.0

  # Audio playback and communication
  audioplayers: ^6.4.0
  flutter_webrtc: ^0.14.0
  janus_client: ^2.3.8

  # Device and permissions
  permission_handler: ^11.0.1
  device_info_plus: ^9.0.3
  location: ^5.0.3
  vibration: ^3.1.3
  mobile_scanner: ^6.0.7

  # Firebase and notifications
  firebase_core: ^3.13.0
  firebase_messaging: ^15.2.5
  flutter_local_notifications: ^19.1.0

  # Authentication
  sign_in_with_apple: ^6.1.0

  # Utilities
  logging: ^1.3.0
  intl: ^0.19.0
  collection: ^1.18.0

  # Security for API
  crypto: ^3.0.3

  # UI
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/sounds/
    - assets/config/
